In [ ]:
import numpy as np
import pandas as pd
import matplotlib

In [ ]:
import random
from datetime import datetime

inicio = datetime(2023, 1, 30)
final =  datetime(2023, 5, 28)

puerta = ['entrando', 'saliendo']

hora =[]
sentido = []

for i in range(30):
  random_date = inicio + (final - inicio) * random.random()
  hora.append(random_date.strftime("%m/%d/%Y, %H:%M"))

  random_sentido = random.choice(puerta)
  sentido.append(random_sentido)

In [ ]:
data = {    
   'Fecha y Hora' : hora,
   'Sentido' : sentido
}
pd.DataFrame(data)

         Fecha y Hora   Sentido
0   05/08/2023, 04:08  saliendo
1   02/03/2023, 05:03  entrando
2   02/07/2023, 22:39  entrando
3   03/30/2023, 13:52  entrando
4   04/28/2023, 07:57  entrando
5   05/23/2023, 09:22  saliendo
6   02/09/2023, 23:00  saliendo
7   05/05/2023, 18:57  saliendo
8   02/19/2023, 02:12  entrando
9   03/18/2023, 19:16  entrando
10  04/14/2023, 08:45  saliendo
11  03/18/2023, 09:24  entrando
12  02/25/2023, 06:26  saliendo
13  05/24/2023, 19:51  entrando
14  03/23/2023, 22:56  entrando
15  03/02/2023, 01:06  entrando
16  02/01/2023, 17:54  saliendo
17  02/23/2023, 02:38  entrando
18  04/29/2023, 16:20  entrando
19  05/09/2023, 06:37  entrando
20  05/23/2023, 20:52  entrando
21  02/21/2023, 13:33  saliendo
22  02/09/2023, 11:02  saliendo
23  04/12/2023, 16:51  entrando
24  03/14/2023, 11:09  saliendo
25  03/23/2023, 19:08  entrando
26  04/01/2023, 23:50  saliendo
27  05/27/2023, 21:59  saliendo
28  01/31/2023, 15:31  entrando
29  03/26/2023, 21:05  saliendo